# Generated by Django 5.1.7 on 2025-06-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_company_documentupload_emissionscope_emissiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='users', to='home.company'),
        ),
    ]
